### ISSUE TITLE
Question: Indexmap and CLion

### ISSUE THREAD

**Issue by PierreHenry63** [bluss/indexmap#148]
Hello,

Thanks for the excellent crate!

I have one question related to the usage of the crate with JetBrains CLion. Somehow the intellisense doesn't work very nicely with it, and the IDE doesn't recognise the output types of functions such as IndexMap::get(). Is there anything that can be done to improve that experience?

Thanks a lot

**Comment by cuviper** [comment]
I suspect this is probably failing because the IDE doesn't have the `has_std` flag from running our build script, which then disables anything that needs the default `S = RandomState`, including `IndexMap::new`. I ran into this with rust-analyzer myself, reported in rust-analyzer/rust-analyzer#5353. They have a `loadOutDirsFromCheck` option to get those build script flags, so maybe JetBrains CLion has something similar?

This seems like another vote for an explicit "std" feature (#145), and cc #135 for 2.0 considerations.

**Comment by aschmolck** [comment]
Any update on this? I've changed some code to use IndexMap for a core data structure, and it basically completely breaks IDE functionality.  I've added "std" explicitly to features in Cargo.toml (as per linked bug #145), but that seems to have no effect, anything that I get out of an IndexMap is a complete mystery to the IDE.

**Comment by cuviper** [comment]
It works for me with Vim and rust-analyzer, but I don't have CLion to try. Can you ask JetBrains for support?

**Comment by aschmolck** [comment]
Thanks -- I will try vim and/or vscode and if the problem is Jetbrains specific file a bug with the Jetbrains Rust plugin.

**Comment by bluss** [comment]
In a way, this is "not an indexmap bug", but it's clear that our usage of autocfg has multiple issues as downside and this should inform our 2.0 version (to not use the same solution for the 'std' flag).

**Comment by bluss** [comment]
We're taking the `std` change as a necessary one, from this issue (among others).
