### ISSUE TITLE
OccupiedEntry::key() gives the new key instead of the old one

### ISSUE THREAD

**Issue by ExpHP** [bluss/indexmap#169]
```rust
struct Item { value: i32, id: &'static str }

impl PartialEq for Item {
    fn eq(&self, other: &Item) -> bool { self.value == other.value }
}
impl Eq for Item {}
impl std::hash::Hash for Item {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.value.hash(state);
    }
}


fn main() {
    use indexmap::map::{IndexMap as Map, Entry};

    let mut map = Map::new();
    map.insert(Item { value: 3, id: "old" }, 200);
    
    match map.entry(Item { value: 3, id: "new" }) {
        Entry::Vacant(e) => panic!(),
        Entry::Occupied(e) => println!("{}", e.key().id),
    }
}
```
**output:**
```
new
```

Whereas if you instead `use std::collections::hash_map::{HashMap as Map, Entry};` then it prints `old`.  This difference in behavior seems surprising.

**Comment by cuviper** [comment]
Hmm, it's been that way forever (638ec3b1f0cad2f5f0701352e4fd88e9bb658bc7), but I agree it would be better to follow `std`'s example.

I worry whether such a behavior change should be considered breaking though...

**Comment by bluss** [comment]
Makes sense to change this. Did this cause a bug on your end or something (so that it's actually something some users would notice?)

**Comment by ExpHP** [comment]
It is something that can have an observable effect, which did cause a bug for me in my case.  I have these types:

```rust
// something with source code location attached
pub struct Spanned<T> {
    span: Span,   // not included in Eq/PartialEq/Hash. Used in diagnostics
    value: T,
}

pub enum Value {
    Array(Vec<Spanned<Value>>),
    Object(IndexMap<Spanned<Ident>, Spanned<Value>>),
    // other variants...
}
```

When deserializing the `Value::Object` variant and I encounter a duplicate key, I want to create an error pointing to both the duplicate and original items.  So I was doing

```rust
let new_span = key.span;
match map.entry(key) {
    Entry::Vacant(entry) => { entry.insert(value); }
    Entry::Occupied(entry) => {
        // here I expected new_span to be the duplicate's span
        // and entry.key().span to be the original's span...
    }
}
```

But that also of course means that this would in some way be a breaking change.  I'm not sure what the case would be for having it return the new key (at least in borrowed form; I *do* see a use for recovering ownership of the new key), I can't deny that there may be code somewhere out there depending on it.

**Comment by cuviper** [comment]
I think it's a sort of grey area where we can argue that this is a bug fix, since the intent has been to follow the API of the standard `HashMap` as much as possible. (queue [xkcd 1172](https://xkcd.com/1172/))

One argument with an eye toward the future -- [`Entry::insert`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.insert) necessarily consumes the key for the insertion, which leaves you with an `OccupiedEntry` that doesn't have a copy of the key at all, so the field is an `Option<K>`. I suppose you could still have `OccupiedEntry::key` try that field first and fall back to the key in the map, but it would be more consistent to just use the key in the map every time. This is also a problem for `replace_entry` and `replace_key`, which currently unwrap that option -- https://github.com/rust-lang/rust/issues/65225#issuecomment-571584668.
