### ISSUE TITLE
It could be much easier for static analyzers to understand indexmap if the `has_std` is not generated by the build script

### ISSUE THREAD

**Issue by architect-z** [bluss/indexmap#184]
Instead we can just use features.

FYI: https://github.com/intellij-rust/intellij-rust/issues/4631

**Comment by bluss** [comment]
The build script feature flag has unfortunately been a headache, but it was made that way to avoid breaking changes in the release 1.x series. You can now use the explicit std feature (but there is no explicit way to say "no std").

**Comment by mike-kfed** [comment]
Seems like the build.rs is gone in master - yay, rooting for a new release :)
I just ran into this issue. Indexmap 1.9.1 is a deep dependency and our CI failed when using rustc flags that ensure our code-quality requirements. If you want to see what I mean, run this `cargo new test && cd test && cargo add dicom && RUSTFLAGS="-D missing_docs" cargo build` produces a documentation unrelated compiler error because of build.rs. Switching to normal Cargo.toml features, i.e. master branch, fixes the problem.
Somehow the missing_docs makes the build.rs believe std is not available... (I guess because the indexmap crate itself doesn't build with that flag)
Anyways workaround for other CI users `export CARGO_FEATURE_STD="std"`, helps others hopefully.
