### ISSUE TITLE
Updating to hashbrown 0.12.0

### ISSUE THREAD

**Issue by erickt** [bluss/indexmap#217]
Would it be possible to update the hashbrown dependency to 0.12.0? We're going through an [audit of indexmap and hashbrown](https://fxrev.dev/612985), and we noticed that in hashbrown 0.12.0 they marked `RawTable::insert_no_grow` as unsafe: https://github.com/rust-lang/hashbrown/pull/254.

I made an attempt at doing an update, but I'm having trouble telling how [`erase_indices`](https://github.com/bluss/indexmap/blob/master/src/map/core.rs#L360) and [`rebuild_hash_table`](https://github.com/bluss/indexmap/blob/master/src/map/core.rs#L430) guarantee that the `indices` table has enough space to use `insert_no_grow`. Do you know what maintains these invariants? Or should we just switch those locations to use `RawTable::insert`?

**Comment by cuviper** [comment]
> Would it be possible to update the hashbrown dependency to 0.12.0?

I hesitate to do this too soon because it bumps MSRV to 1.56, and we already have folks complaining about 1.49 (#214).

> we noticed that in hashbrown 0.12.0 they marked `RawTable::insert_no_grow` as unsafe: [rust-lang/hashbrown#254](https://github.com/rust-lang/hashbrown/pull/254).

Yes, that was me. :) AFAIK our current usage already meets those unsafe conditions anyway, so there shouldn't be any functional difference for us between 0.11 and 0.12, but I welcome you to confirm that independently.

> I made an attempt at doing an update, but I'm having trouble telling how [`erase_indices`](https://github.com/bluss/indexmap/blob/master/src/map/core.rs#L360) and [`rebuild_hash_table`](https://github.com/bluss/indexmap/blob/master/src/map/core.rs#L430) guarantee that the `indices` table has enough space to use `insert_no_grow`. Do you know what maintains these invariants?

Both of these are conditions where we just cleared the table and then we are reinserting the same or fewer entries. If there's any question whether that's actually true, I suppose we could add a runtime `assert!` to make sure of it. A single check shouldn't affect performance much, versus repeated `insert` checks and all its extra codegen for resizing that we shouldn't need.

**Comment by paolobarbolini** [comment]
> I hesitate to do this too soon because it bumps MSRV to 1.56, and we already have folks complaining about 1.49 (https://github.com/bluss/indexmap/issues/214).

Could we reconsider this now that 1.56 is 6 months old?

**Comment by cuviper** [comment]
Well, I already upgraded on master in preparation for v2, #219. I think we need to decide on #147 though before release, because adding generic parameters will break some uses, IIRC, even with a default. I'd like #177 too, but there's nothing breaking there.

**Comment by tustvold** [comment]
Rust 1.56 has now been out for the best part of 8 months now, are there any plans to release a 1.x version that bumps the dependency?

**Comment by cuviper** [comment]
I had no plans for 1.x, but we can do it -- see #231.
